name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Check bundle size
      run: |
        if [ -f dist/index.umd.js ]; then
          SIZE=$(gzip -c dist/index.umd.js | wc -c)
          if [ $SIZE -gt 15360 ]; then
            echo "Bundle size $SIZE bytes gzipped exceeds 15KB limit"
            exit 1
          fi
          echo "Bundle size: $SIZE bytes gzipped"
        fi